name: ci-cd
on:
  push:
    paths-ignore:
      - "**.md"
      - "images/**"
      - ".gitignore"

permissions:
  id-token: write
  packages: read
  contents: write
  pull-requests: read

jobs:
  list-modules:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Git checkout
        uses: actions/checkout@v4

      - id: set-matrix
        run: |
          JSON=$(jq -c . < ./.github/workflows/module.json)
          echo "Matrix contents: $JSON"
          echo "matrix=$JSON" >> $GITHUB_OUTPUT
  plan-regional:
    needs: [list-modules]
    uses: ./.github/workflows/_plan-regional.yml
    strategy:
      fail-fast: false
      matrix: ${{ fromJSON(needs.list-modules.outputs.matrix) }}
    with:
      environment: ${{ inputs.environment }}
      module: ${{ matrix.module }}
